In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_excel("/content/drive/MyDrive/dataset_multiple_LR.xlsx")
print(df)

    Age  Weight  Blood Pressure
0    52     173             132
1    59     184             143
2    67     194             153
3    73     211             162
4    64     196             154
5    74     220             168
6    54     188             137
7    61     188             149
8    65     207             159
9    46     167             128
10   72     217             166


In [ ]:
data = df.to_numpy()
print(data)

[[ 52 173 132]
 [ 59 184 143]
 [ 67 194 153]
 [ 73 211 162]
 [ 64 196 154]
 [ 74 220 168]
 [ 54 188 137]
 [ 61 188 149]
 [ 65 207 159]
 [ 46 167 128]
 [ 72 217 166]]


In [ ]:
X = data[:,0:2]
print(X)

[[ 52 173]
 [ 59 184]
 [ 67 194]
 [ 73 211]
 [ 64 196]
 [ 74 220]
 [ 54 188]
 [ 61 188]
 [ 65 207]
 [ 46 167]
 [ 72 217]]


In [ ]:
Y = data[:,2].reshape(-1,1)
print(Y)

[[132]
 [143]
 [153]
 [162]
 [154]
 [168]
 [137]
 [149]
 [159]
 [128]
 [166]]


In [ ]:
X0 = np.ones(11).reshape(-1,1)
print(X0)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
X = np.append(X0,X, axis = 1)
print(X)

[[  1.  52. 173.]
 [  1.  59. 184.]
 [  1.  67. 194.]
 [  1.  73. 211.]
 [  1.  64. 196.]
 [  1.  74. 220.]
 [  1.  54. 188.]
 [  1.  61. 188.]
 [  1.  65. 207.]
 [  1.  46. 167.]
 [  1.  72. 217.]]


In [ ]:
def transpose (X):
  result = np.zeros(len(X)*len(X[0])).reshape(len(X[0]),len(X))
  for j in range(len(X)):
    for i in range(len(X[0])):
      result[i,j] = X[j, i]
  return result

In [ ]:
XT = transpose(X)
print(XT)

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [ 52.  59.  67.  73.  64.  74.  54.  61.  65.  46.  72.]
 [173. 184. 194. 211. 196. 220. 188. 188. 207. 167. 217.]]


In [ ]:
def myMulti(res,b):
  value=np.zeros(len(res)*len(res)).reshape(len(res),len(res))
  for i in range(len(res)):
    for j in range(len(b[0])):
      for k in range(len(b)):
        value[i][j]+=res[i][k]*b[k][j]
  return value

In [ ]:
np.set_printoptions(suppress=True)
A=myMulti(XT,X)
print(A)

[[    11.    687.   2145.]
 [   687.  43737. 135458.]
 [  2145. 135458. 421273.]]


In [ ]:
C=myMulti(XT,Y)
print(C)

[[  1651.      0.      0.]
 [104328.      0.      0.]
 [324235.      0.      0.]]


In [ ]:
def determ(a):
  deter=0
  for i in range(len(a)):
      deter+=(a[0][i] * (a[1][(i+1)%3] * a[2][(i+2)%3] - a[1][(i+2)%3] * a[2][(i+1)%3]))
  return deter



In [ ]:
d=determ(A)
d

2876185.0

In [ ]:
def cofac(a):
  cof2=np.zeros(len(a)*len(a)).reshape(len(a),len(a))
  for i in range(len(a)):
    for j in range(len(a)):
      cof2[i][j]=((a[(j+1)%3][(i+1)%3] * a[(j+2)%3][(i+2)%3]) - (a[(j+1)%3][(i+2)%3] * a[(j+2)%3][(i+1)%3]))
  return cof2

In [ ]:
np.set_printoptions(suppress=True)
cofA=cofac(A)
print(cofA)

[[76347437.  1142859.  -756219.]
 [ 1142859.    32978.   -16423.]
 [ -756219.   -16423.     9138.]]


In [ ]:
adjA=transpose(cofA)
adjA

array([[76347437.,  1142859.,  -756219.],
       [ 1142859.,    32978.,   -16423.],
       [ -756219.,   -16423.,     9138.]])

In [ ]:
def inv(a):
  inverse=np.zeros(len(a)*len(a)).reshape(len(a),len(a))
  for i in range(len(a)):
        for j in range(len(a)):
            inverse[i][j] = adjA[i][j]/d
  return inverse

In [ ]:
iv=inv(A)
iv

array([[26.54468923,  0.3973524 , -0.26292433],
       [ 0.3973524 ,  0.01146588, -0.00570999],
       [-0.26292433, -0.00570999,  0.00317713]])

In [ ]:
np.set_printoptions(suppress=True)
W=myMulti(iv,C)
W

array([[30.99410295,  0.        ,  0.        ],
       [ 0.86141469,  0.        ,  0.        ],
       [ 0.3348592 ,  0.        ,  0.        ]])